js2svg:
  pretty: true
  indent: '  '
multipass: true
plugins:
  - addAttributesToSVGElement:
      attributes:
        - focusable: false
        - 'height'
        - 'width'
  - convertColors:
      currentColor: 'red'
  - inlineStyles:
      onlyMatchedOnce: false
  - removeAttrs:
      attrs:
        - 'baseProfile'
        - 'class'
        - 'clip-rule'
        - 'id'
        - 'stroke-miterlimit'
        - 'version'
  - removeTitle: true
  - removeViewBox: false
  - removeUnknownsAndDefaults:
      unknownAttrs: false
  - sortAttrs: true
